title: Gustavo V. Barroso
baseurl: ""
url: "http://gvbarroso.github.io"
logo: "/images/photo.jpg?raw=true"
markdown: kramdown
github_username: gvbarroso
twitter_username: gv_barroso

description: >
  Los Angeles, CA, USA
  <br><br>
  I study evolutionary biology using computational methods.
  My long-term goal is to understand how population-level processes
  (genetic drift, natural selection) interact with molecular-level processes
  (mutation, recombination) to shape patterns of genetic variation.
  To this end, I develop statistical models based on population genetics theory.
  I build these models into inference tools using a combination of the C++ and R
  programming languages and apply them to both simulated and empirical data sets
  from a variety of species. 

owner:
  github: gvbarroso
  
theme: jekyll-theme-minimal
