title: Gustavo Valadares Barroso
baseurl: ""
url: "http://gvbarroso.github.io"
logo: "/images/photo.jpg?raw=true"
markdown: kramdown

description: >
  email: gvbarroso (at) gmail.com
  <br><br>
  I am an population geneticist working to extract meaningful information from data using mathematics.
  A wet-lab / field biologist by training, I grew interested in statistical modelling
  after my masters. Nowadays, I approach biological questions with computational methods, using a
  combination of the C++ and R programming languages. My long-term goal is to build more realistic models
  of nature. 

owner:
  github: gvbarroso
  
theme: jekyll-theme-minimal

