title: Gustavo V. Barroso
#logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: >
  Computational Evolutionary Biologist
theme: jekyll-theme-slate
orcid_id: https://orcid.org/0000-0002-1943-9297
